version: "3.5"
services:
  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhadebackend
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - rinha-backend-node

  # migration:
  #   image: node:latest
  #   command: sh -c 'echo "running migration..."; npx run knex; sleep 20; echo "migration completed"'
  #   depends_on:
  #     - api1
  #     - api2
  #     - db

  api1: # API - Instância 01
    image: gleisin/node-web-app:latest
    hostname: api1
    restart: always
    # command: bash -c "npm run knex"
    depends_on:
      - db
    expose:
      - "8980"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    networks:
      - rinha-backend-node

  api2: # API - Instância 01
    image: gleisin/node-web-app:latest
    hostname: api2
    restart: always
    # command: bash -c "npm run knex"
    depends_on:
      - db
    expose:
      - "8980"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    networks:
      - rinha-backend-node

  nginx: # Load Balancer
    container_name: nginx2
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    networks:
      - rinha-backend-node

networks:
  rinha-backend-node:
