version: '3.3'
services:
  app:
    build: . # Use o Dockerfile do diretório atual
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3026:3026
    # environment:
    #   NODE_ENV: development # Define a variável de ambiente NODE_ENV como 'development'
